<div id="footer">
    <div class="container">
      <p class="pull-right"><a href="<?php echo $this->url() ?>#top">Back to top</a></p>
      <p>
        Licensed under the <a href="http://opensource.org/licenses/MIT" target="_blank">MIT</a>.
      </p>
    </div>
</div>

<div id="errorModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php $this->_e('Ooops') ?></h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
</div>

<div id="confirmModal" class="modal hide fade">
    <div class="modal-header">
        <h3><?php $this->_e('Confirm your action') ?></h3>
    </div>
    <div class="modal-body">
        <p><?php $this->_e('This is a confirm modal, click confirm button to perform your action') ?></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php $this->_e('Close') ?></button>
        <button class="btn btn-primary" id="confirmYesBtn"><?php $this->_e('Confirm') ?></button>
    </div>
</div>
<?php
    echo $this->headScript();
    echo $this->jqueryScript();
?>