<?php echo $this->doctype(); ?>
<head>
    <base href="/" />
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle() ?>
    <?php
        $this->headLink()->headLink(array('rel' => 'shortcut icon', 'href' => 'favicon.ico', 'type' => 'image/vnd.microsoft.icon'));
        $this->headScript()->prependFile('/components/require.js', 'text/javascript');
        $this->headScript()->appendFile('/js/core.js', 'text/javascript');

        $this->headLink()->appendStylesheet('/components/require.css');
        $this->headLink()->appendStylesheet('/css/style.css');
    ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
