#!/bin/sh
# path to local config file
ZF_CONFIG_FILE="${PWD}/.zf.ini"
export ZF_CONFIG_FILE

# add include_path option
PATH_TO_ZF="${PWD}/vendor/zend/zf1"
ZEND_TOOL_INCLUDE_PATH_PREPEND="${PATH_TO_ZF}/library:${PWD}/library"
export ZEND_TOOL_INCLUDE_PATH_PREPEND

# call vendor zf.sh
$PATH_TO_ZF/bin/zf.sh $@
