<?php echo $this->navigation()->breadcrumbs()->setPartial(array('breadcrumbs.phtml', 'default')); ?>

<div class="hero-unit">
    <div class="page-header">
        <h1><?php echo $this->form->getDescription() ?></h1>
    </div>
    <?php $this->form->setAction($this->url(array(
        'module'=>'user',
        'controller'=>'profile',
        'action'=>'change-password'
    ))) ?>
    <?php $this->form->setAttrib('class', 'form-horizontal') ?>
    <?php echo $this->form ?>
</div>