<?php

/**
 * User_Model_Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Users extends Core_Model_Abstract
{

    const STATUS_REGISTER = 1;
    const STATUS_ACTIVE   = 2;
    const STATUS_BLOCKED  = 0;

    /**
     * Generate hash to password
     *
     * @param string $password
     * @return Doctrine_Record
     */
    public function setPassword($password)
    {
        if (strlen($password) < 32) {
            $salt = $this->generateSalt();
            $this->_set('salt', $salt);
            return $this->_set('password', md5($salt . $password . Zend_Registry::get('static_salt')));
        } else {
            return $this->_set('password', $password);
        }
    }

    /**
     * Create and set dynamic salt for password
     *
     * @return string
     */
    public function generateSalt()
    {
        $salt = null;
        for ($i = 0; $i < 50; $i++) {
            $salt .= chr(rand(33, 126));
        }
        return md5($salt);
    }
}