<?php echo $this->partial('default/partial/header.phtml') ?>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><?php print strip_tags($this->headTitle()) ?></a>
          <div class="nav-collapse collapse">
            <?php //echo $this->navigation()->menu()->setMinDepth(0)->setMaxDepth(0); ?>
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="/#" class="dropdown-toggle" data-toggle="dropdown">Dropdown</a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <a href="/user/authentication/login" class="btn btn-primary pull-right">Sign In</a>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->layout()->content ?>
    </div>
      
    <?php echo $this->partial('default/partial/footer.phtml') ?>
  </body>
</html>
