<?php echo $this->partial('default/partial/header.phtml') ?>

  <body>
    <?php echo $this->partial('default/partial/messenger.phtml') ?>
    <div id="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <a class="brand" href="/"><?php print strip_tags($this->projectTitle()) ?></a>
              <div class="nav-collapse collapse">
                <?php $homeMenu = $this->navigation()->findOneByLabel('Home'); ?>
                <?php echo $this->navigation()->menu()->setMinDepth(0)->setMaxDepth(0)->renderMenu($homeMenu, array('ulClass'=>'nav')); ?>
                <?php echo $this->action('index','authentication','user'); ?>
              </div>
            </div>
          </div>
        </div>

        <div class="container">
          <?php echo $this->layout()->content ?>
        </div>

        <div id="push"></div>
    </div>

    <?php echo $this->partial('default/partial/footer.phtml') ?>
  </body>
</html>
