<?php echo $this->partial('default/partial/header.phtml') ?>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><?php print strip_tags($this->headTitle()) ?></a>
          <div class="nav-collapse collapse">
            <?php //echo $this->navigation()->menu()->setUlClass('nav')->setMinDepth(0)->setMaxDepth(0); ?>
            
            <a href="/user/authentication/login" class="btn btn-primary pull-right">Sign In</a>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->layout()->content ?>
    </div>
      
    <?php echo $this->partial('default/partial/footer.phtml') ?>
  </body>
</html>
