<ul class="breadcrumb">
    <?php echo $this->navigation()->breadcrumbs(); ?>
</ul>
<div class="hero-unit">
    <h1><?php $this->_e('Sign In') ?></h1>
    <hr/>
    <?php $this->form->setAction($this->url(array('module'=>'user','controller'=>'authentication','action'=>'login'))) ?>
    <?php $this->form->setAttrib('class', 'form-horizontal') ?>
    <?php echo $this->form ?>
    
    <?php echo $this->link(
        array(
            'module' => 'user',
            'controller' => 'registration',
            'action' => 'index'
        ),
        $this->__('Registration'),
        array('class' => 'btn btn-link')
    ) ?>
    
    <?php echo $this->link(
        array(
            'module' => 'user',
            'controller' => 'forgot',
            'action' => 'index'
        ),
        $this->__('Forgotten password?'),
        array('class' => 'btn btn-link')
    ) ?>
</div>