<ul class="breadcrumb">
    <?php echo $this->navigation()->breadcrumbs(); ?>
</ul>
<div class="hero-unit">
    <h1><?php $this->_e('Sign In') ?></h1>
    <hr/>
    <?php $this->form->setAction($this->url()) ?>
    <?php $this->form->setAttrib('class', 'form-horizontal') ?>
    <?php $this->form->removeDecorator('HtmlTag') ?>
    <?php echo $this->form ?>
    <a href="/user/registration/index" class="btn btn-link">Registration</a>
    <a href="/user/forgot/index" class="btn btn-link">Forgotten password?</a>
</div>